### ISSUE TITLE
Make create method return shop object instead of integer

### ISSUE THREAD

**Issue by mlan080** [mlan080/tea-shops#50]

**Comment by mlan080** [comment]
**My self answered questions and steps to approach this problem** - Please advise if my thinking is correct/concise enough

Why an instance method instead of a class method? 
Because we do not want to repeat Shop.new everything we want create an object in the database. 

What is currently happening with this create method 
`def create
    shops = DB[:shops]
    shops.insert(:name => name, :description => description)
  end`

Accessing the database and storing it in `shops` variable. Using the insert method to add the element to the hash. The :name is the column name and name is the method accessing the instance variable name (as defined in the attr_accessor)

Why does it return an integer? 
The create method is a POST request and it returns an integer with the insert function? 

Why do we want it to return an shop object? 
Because .create in rails returns a shop object so my method should behave the same. Also Shop.new returns an object too. 

Steps 
1.  Create a new shop object `Shop.new` and input a name and description like this 
` a = Shop.new(name: 'hel', description: 'haha')`
2. call `a.create` to insert new ID into the database with this name and description. 

**Questions** 
So do we need to specify can input and put this Shop.new(name: name, description: description) inside? 

Can you check if the below is what we are trying to achieve? Obviously I can't use another method cause it's not reliable. 

  def create
    shops = DB[:shops]
   # s = Shop.new(:name => name, :description => description)
    shop = shops.insert(:name => name, :description => description)
    Shop.last

  end

**Comment by actfong** [comment]
Hey @mlan080 

Regarding the `instance- v class-method` thing. TBH, i think for the `create` method, it could be either.
In Rails, the create method is a class method e.g. `Shop.create(name: 'my teashop')`
And what that class method does, is doing something similar to
```
# instantiation
obj = Shop.new(name: 'my teashop')
# persistance
obj.save 
# return the object after its saved state
obj
```
In your case, `shops.insert(attrs)` is the persistence part.

TBH, i think it is OK for you to continue your create method as an instance method. So my comments below are based on the idea that you will continue on the instance method path.

I think the 2 suggestions of the instance method `create` is almost there. Your thinking already contains the steps of instantiation and persistence as above ☝️ 

The only thing that you are missing are:
1  returning the object correctly at the end
2  instantiation is not needed in your case, because you are writing an instance method (you already have an instance)

In your first example, you are returning the object with `Shop.last`. What if someone else has just inserted another shop just before you ran Shop.last, then you will get his/her Shop.
In your second example, you are trying to instantiate a shop again, but with an id.
A much better way would be just to retrieve the object based on the id you have

```
def create
  shops = DB[:shops]
  # persistence. `self` here refers that the object calling the create method
  id =  shops.insert(name: self.name, description: self.description)
  # return the shop object
  Shop.find(id)
end
```

Give this a go, and see whether it works for you

**Comment by actfong** [comment]
One more comment

    Why does it return an integer?
    The create method is a POST request and it returns an integer with the insert function?

It has nothing to do with POST request here. You can see the documentation/source-code here
https://github.com/jeremyevans/sequel/blob/master/lib/sequel/dataset/actions.rb#L359

**Comment by mlan080** [comment]
> def create # persistence. # `self` here refers that the object calling the create method id = DB[:shops].insert(name: self.name, description: self.description) # return the shop object Shop.find(id) end

Yes this does return the object as we wanted. However I thought was a bad idea to use another method (find) in case it breaks.

**Comment by actfong** [comment]
@mlan080 

> However I thought was a bad idea to use another method (find) in case it breaks.
That's why we have tests ;)

It is not a bad idea to use another method. It is common, otherwise we would have methods longer than 100 lines everywhere 😂 

So for you, it is important to test not only the attributes of the created object (name, description), but also the type of the returned object (ensure it is of the class Shop).

I think you should know enough for now to proceed
